name: buscomfy_flutter_app
description: A Flutter project for the Buscomfy app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:                        # ✅ Must be indented under `flutter`
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
