name: buscomfy_new
description: A new Flutter project for the Buscomfy App
publish_to: 'none' # Remove this if publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Uncomment and adjust if needed:
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/fonts/
